name: checkstyle (Perl)
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  checkstyle-perl:
    runs-on: ubuntu-latest
    container:
      image: perl:5.42
    steps:
      - uses: actions/checkout@v5
      - name: Fix git permissions
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: cpanm -n Perl::Tidy CPAN::Audit
      - name: perltidy --version
        run: perltidy --version
      - name: Run checkstyle
        run: make checkstyle-perl
