---
name: eslint
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  test:
    if: false  # disabled because currently failing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: '22'
    - name: npm install
      run: npm install --ignore-scripts
    - name: npm run lint
      run: npm run lint
